import { useState, useMemo, useEffect } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Slider } from "@/components/ui/slider";
import { CheckCircle2, ChevronRight, RotateCcw, Lightbulb, MessageCircleQuestion, TrendingUp, TrendingDown, Minus } from "lucide-react";
import LabIntro from "./LabIntro";
import type { LabIntroData } from "./LabIntro";

/**
 * DynamicLab — A flexible catch-all renderer for AI-generated labs.
 * 
 * Renders any lab_data that has:
 * - parameters + decisions (simulation-style)
 * - tasks (task-based)
 * - decisions without parameters (pure decision-based)
 * - or any combination
 * 
 * This component exists so that creative/unknown lab types
 * generated by the AI still render properly.
 */

type Props = {
  data: any;
  onComplete?: () => void;
  isCompleted?: boolean;
};

function getParamLevel(value: number, min: number, max: number) {
  const pct = ((value - min) / (max - min)) * 100;
  if (pct >= 75) return { color: "text-green-500", icon: TrendingUp };
  if (pct >= 35) return { color: "text-yellow-500", icon: Minus };
  return { color: "text-red-500", icon: TrendingDown };
}

export default function DynamicLab({ data, onComplete, isCompleted }: Props) {
  const hasParameters = Array.isArray(data?.parameters) && data.parameters.length > 0;
  const hasDecisions = Array.isArray(data?.decisions) && data.decisions.length > 0;
  const hasTasks = Array.isArray(data?.tasks) && data.tasks.length > 0;
  const hasIntro = !!data?.repend_intro;

  const parameters = useMemo(() => data?.parameters ?? [], [data]);
  const decisions = useMemo(() => {
    if (!hasDecisions) return [];
    return (data.decisions || []).map((d: any) => ({
      ...d,
      question: d.question || d.prompt || "What do you decide?",
      emoji: d.emoji || "🔬",
      choices: Array.isArray(d.choices) ? d.choices : [],
    }));
  }, [data, hasDecisions]);

  const [showIntro, setShowIntro] = useState(true);
  const [values, setValues] = useState<Record<string, number>>({});
  const [currentDecision, setCurrentDecision] = useState(0);
  const [answered, setAnswered] = useState<Record<number, number>>({});
  const [taskAnswers, setTaskAnswers] = useState<Record<string, string>>({});
  const [showTaskResults, setShowTaskResults] = useState(false);
  const [completionFired, setCompletionFired] = useState(false);

  useEffect(() => {
    if (hasParameters) {
      const initial = Object.fromEntries(parameters.map((p: any) => [p.name, p.default ?? 50]));
      setValues(initial);
    }
    setCurrentDecision(0);
    setAnswered({});
    setTaskAnswers({});
    setShowTaskResults(false);
    setCompletionFired(false);
    setShowIntro(true);
  }, [data]);

  const totalPercent = useMemo(() => {
    if (!parameters.length) return 0;
    const total = parameters.reduce((sum: number, p: any) => {
      const pct = ((values[p.name] ?? p.default ?? 50) - (p.min ?? 0)) / ((p.max ?? 100) - (p.min ?? 0));
      return sum + pct;
    }, 0);
    return Math.round((total / parameters.length) * 100);
  }, [values, parameters]);

  const thresholds = useMemo(() => data?.thresholds ?? [], [data]);
  const threshold = useMemo(() => {
    if (!thresholds.length) return null;
    const sorted = [...thresholds].sort((a: any, b: any) => b.min_percent - a.min_percent);
    return sorted.find((t: any) => totalPercent >= t.min_percent) || sorted[sorted.length - 1];
  }, [totalPercent, thresholds]);

  const allDecisionsDone = decisions.length > 0 && Object.keys(answered).length === decisions.length;
  const allTasksDone = hasTasks && Object.keys(taskAnswers).length === data.tasks.length;
  const isComplete = (hasDecisions ? allDecisionsDone : true) && (hasTasks ? allTasksDone : true);

  useEffect(() => {
    if (isComplete && !completionFired && onComplete && (hasDecisions || hasTasks)) {
      onComplete();
      setCompletionFired(true);
    }
  }, [isComplete, completionFired, onComplete]);

  const handleDecision = (dIdx: number, cIdx: number) => {
    if (answered[dIdx] !== undefined) return;
    const choice = decisions[dIdx]?.choices[cIdx];
    if (!choice) return;

    if (hasParameters && choice.set_state) {
      setValues((prev) => {
        const next = { ...prev };
        for (const p of parameters) {
          next[p.name] = Math.max(0, Math.min(100, choice.set_state[p.name] ?? prev[p.name] ?? p.default ?? 50));
        }
        return next;
      });
    }

    setAnswered((prev) => ({ ...prev, [dIdx]: cIdx }));
  };

  const reset = () => {
    if (hasParameters) {
      const initial = Object.fromEntries(parameters.map((p: any) => [p.name, p.default ?? 50]));
      setValues(initial);
    }
    setCurrentDecision(0);
    setAnswered({});
    setTaskAnswers({});
    setShowTaskResults(false);
    setCompletionFired(false);
    setShowIntro(true);
  };

  // Already completed state
  if (isCompleted && !isComplete) {
    return (
      <Card className="border-green-500/20 bg-green-500/[0.04]">
        <CardContent className="p-6 text-center space-y-3">
          <CheckCircle2 className="w-10 h-10 text-green-500 mx-auto" />
          <h3 className="font-bold text-lg">Lab Complete</h3>
          <p className="text-sm text-muted-foreground">You've already completed this lab.</p>
          <Button variant="outline" onClick={reset}>
            <RotateCcw className="w-4 h-4 mr-1" /> Replay Lab
          </Button>
        </CardContent>
      </Card>
    );
  }

  // Intro screen
  if (showIntro && hasIntro) {
    return (
      <LabIntro
        title={data.title || "Interactive Lab"}
        intro={data.repend_intro as LabIntroData}
        labType={data.lab_type_hint || "simulation"}
        onStart={() => setShowIntro(false)}
      />
    );
  }

  if (showIntro && !hasIntro) {
    const introText = data.intro || data.description || `In this lab, you'll explore ${data.title || "the concept"} through interactive decisions.`;
    return (
      <Card className="border-primary/20 bg-primary/5">
        <CardContent className="p-5 space-y-4">
          <div className="flex items-center gap-2">
            <span className="text-2xl">🧪</span>
            <h3 className="font-bold text-lg">{data.title || "Interactive Lab"}</h3>
          </div>
          <p className="text-sm leading-relaxed">{introText}</p>
          {hasParameters && (
            <div className="space-y-2">
              <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">Variables</span>
              <div className="flex flex-wrap gap-2">
                {parameters.map((p: any) => (
                  <Badge key={p.name} variant="outline" className="text-xs">
                    {p.icon} {p.name}
                  </Badge>
                ))}
              </div>
            </div>
          )}
          <Button onClick={() => setShowIntro(false)} className="w-full">
            Start Lab <ChevronRight className="w-4 h-4 ml-1" />
          </Button>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-5">
      {/* DECISIONS */}
      {hasDecisions && !allDecisionsDone && currentDecision < decisions.length && (
        <Card className="border-primary/30 bg-primary/5">
          <CardContent className="p-5 space-y-4">
            <div className="flex items-center gap-2">
              <MessageCircleQuestion className="w-5 h-5 text-primary" />
              <h3 className="font-bold">
                Scenario {currentDecision + 1} of {decisions.length}
              </h3>
            </div>
            <p>{decisions[currentDecision].emoji} {decisions[currentDecision].question}</p>
            {decisions[currentDecision].choices.map((c: any, i: number) => {
              const isChosen = answered[currentDecision] === i;
              const isAnswered = answered[currentDecision] !== undefined;
              return (
                <div key={i} className="space-y-1">
                  <button
                    onClick={() => handleDecision(currentDecision, i)}
                    disabled={isAnswered}
                    className={`w-full text-left px-4 py-3 rounded-lg border text-sm transition ${
                      isChosen ? "border-primary bg-primary/10" : isAnswered ? "opacity-50 border-border" : "border-border hover:border-primary/40"
                    }`}
                  >
                    {c.text}
                  </button>
                  {isChosen && (c.explanation || c.consequence) && (
                    <p className="text-xs text-muted-foreground px-4 py-2 bg-muted/50 rounded-md">
                      ⚡ {c.explanation || c.consequence}
                    </p>
                  )}
                </div>
              );
            })}
            {answered[currentDecision] !== undefined && currentDecision < decisions.length - 1 && (
              <Button size="sm" variant="outline" onClick={() => setCurrentDecision((prev) => prev + 1)}>
                Next →
              </Button>
            )}
          </CardContent>
        </Card>
      )}

      {/* PARAMETER SLIDERS */}
      {hasParameters && parameters.map((p: any) => {
        const value = values[p.name] ?? p.default ?? 50;
        const { color, icon: Icon } = getParamLevel(value, p.min ?? 0, p.max ?? 100);
        return (
          <Card key={p.name}>
            <CardContent className="p-4 space-y-3">
              <div className="flex justify-between items-center">
                <div className="flex gap-2 items-center">
                  <span>{p.icon}</span>
                  <span>{p.name}</span>
                </div>
                <div className="flex items-center gap-2">
                  <Icon className={`w-4 h-4 ${color}`} />
                  <Badge variant="outline">{value} {p.unit}</Badge>
                </div>
              </div>
              <Slider value={[value]} min={p.min ?? 0} max={p.max ?? 100} step={1} disabled className="pointer-events-none" />
              {p.description && <p className="text-xs text-muted-foreground">{p.description}</p>}
            </CardContent>
          </Card>
        );
      })}

      {/* TASKS */}
      {hasTasks && !showTaskResults && (
        <Card className="border-primary/20">
          <CardContent className="p-5 space-y-4">
            <h3 className="font-bold">📋 Tasks</h3>
            {data.tasks.map((task: any) => (
              <div key={task.id} className="space-y-2">
                <p className="text-sm font-medium">{task.description}</p>
                {task.type === "choice" && Array.isArray(task.options) ? (
                  <div className="space-y-1">
                    {task.options.map((opt: string, i: number) => (
                      <button
                        key={i}
                        onClick={() => setTaskAnswers((prev) => ({ ...prev, [task.id]: opt }))}
                        className={`w-full text-left px-3 py-2 rounded border text-sm transition ${
                          taskAnswers[task.id] === opt ? "border-primary bg-primary/10" : "border-border hover:border-primary/40"
                        }`}
                      >
                        {opt}
                      </button>
                    ))}
                  </div>
                ) : (
                  <input
                    type="text"
                    placeholder="Your answer..."
                    value={taskAnswers[task.id] || ""}
                    onChange={(e) => setTaskAnswers((prev) => ({ ...prev, [task.id]: e.target.value }))}
                    className="w-full px-3 py-2 rounded border border-border bg-background text-sm"
                  />
                )}
              </div>
            ))}
            {Object.keys(taskAnswers).length === data.tasks.length && (
              <Button onClick={() => setShowTaskResults(true)} className="w-full">
                Check Answers
              </Button>
            )}
          </CardContent>
        </Card>
      )}

      {/* TASK RESULTS */}
      {showTaskResults && hasTasks && (
        <Card className="border-green-500/20">
          <CardContent className="p-5 space-y-3">
            <h3 className="font-bold">📋 Results</h3>
            {data.tasks.map((task: any) => {
              const userAnswer = taskAnswers[task.id] || "";
              const correct = String(task.correct_answer || "").toLowerCase();
              const isCorrect = userAnswer.toLowerCase().trim() === correct.trim();
              return (
                <div key={task.id} className="space-y-1">
                  <p className="text-sm font-medium">{task.description}</p>
                  <p className="text-xs">
                    Your answer: <span className={isCorrect ? "text-green-500" : "text-red-500"}>{userAnswer}</span>
                    {!isCorrect && <span className="text-muted-foreground"> (Correct: {task.correct_answer})</span>}
                  </p>
                </div>
              );
            })}
          </CardContent>
        </Card>
      )}

      {/* OUTCOME */}
      {hasParameters && allDecisionsDone && (
        <Card>
          <CardContent className="p-5">
            <div className="flex justify-between mb-2">
              <span className="font-bold">{threshold?.label ?? "Outcome"}</span>
              <Badge>{totalPercent}%</Badge>
            </div>
            <div className="h-2 bg-secondary rounded-full overflow-hidden">
              <div className="h-full bg-primary transition-all" style={{ width: `${totalPercent}%` }} />
            </div>
            {threshold?.message && <p className="text-sm text-muted-foreground mt-2">{threshold.message}</p>}
          </CardContent>
        </Card>
      )}

      {/* Key Insight */}
      {isComplete && data.key_insight && (
        <Card className="border-primary/20 bg-primary/5">
          <CardContent className="p-5 space-y-2">
            <div className="flex items-center gap-2">
              <Lightbulb className="w-5 h-5 text-primary" />
              <h3 className="font-bold">✅ Key Insight</h3>
            </div>
            <p className="text-sm leading-relaxed">{data.key_insight}</p>
          </CardContent>
        </Card>
      )}

      {/* Reset */}
      {isComplete && (
        <Button variant="outline" onClick={reset}>
          <RotateCcw className="w-4 h-4 mr-1" /> Replay Lab
        </Button>
      )}
    </div>
  );
}
